### ISSUE TITLE
UFAL/PY-resourcepolicy old 18320 != new 15435

### ISSUE THREAD

**Issue by milanmajchrak** [dataquest-dev/dspace-python-api#83]

**Comment by MajoBerger** [comment]
In clarin DSpace for each item there are several resource policies, that are not necessary, since in DSpace 7.5 those policies are hierarchical.

**Comment by Paurikova2** [comment]
Notes:
Where does the resourcepolisy create?
1. Community
create community (CommunityServiceImpl [120] -> Anonymous - READ)
create community administrator -> delete default policy and create new
Result: 9 new added policy -> 8 anonymous, 1 admin group
Notes: Praha data contains 7 anonymous and 2 admin groups (44, 57), but if the community has admin group, it should be in its attribute admin. And in Praha data, there is only one community with `admin` attribute filled: community with id 44. That's the reason why there is incompatibility between resourcepolicy in their data and our data connected with community.

2 Collection
create collection (CollectionServiceImpl [139] -> Anonymous - READ, DEFAULT_ITEM_READ, DEFAULT_BITSTREAM_READ
create workflowrole -> collection workflow_step_2 ->XmlWorkflowServiceImpl [188] -> ADD
                                - > submitter -> CollectionServiceImpl [509] -> ADD
coll2group -> CollectionServiceImpl [938] -> remove existing privileges from anonymous group and add DEFAULT_BITSTREAM_READ and DEFAULT_ITEM_READ  -> WORKS

Collections: missing 6

3. Items
create - WorkspaceItemServiceImpl [124] -> READ, WRITE, ADD, REMOVE, DELETE (type TYPE_SUBMISSION)
grantGroupAllItemPolicies - XmlServiceImpl -> calling from importWorkflowItem -> READ, WRITE, DELETE, ADD, REMOVE

**Comment by MajoBerger** [comment]
There are differences between some resourcepolicies. As named in import Statistics:

expected = number of rows in old (5.2) database
imported = number of rows in new (7.5) database
duplicated = policy DEFAULT_READ from old DSpace is now divided into DEFAULT_BITSTREAM_READ and DEFAULT_ITEM_READ. Therefore for each one such resource policy in old DSpace, there are two new policies in new DSpace.
unimported = amongst other things, most importantly this number inclues such resource policies from old dspace, that related to an item no longer existing. Therefore REST API did not allow importing such resource policy.

**Comment by MajoBerger** [comment]
Should be checked here

https://github.com/dataquest-dev/dspace-python-api/issues/105

**Comment by milanmajchrak** [comment]
It is developed here: https://github.com/dataquest-dev/dspace-python-api/issues/101
